{
 "title": "OpenEdge",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Sports2020 Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Commits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DB_testvm_20000_sports2020_SummaryCommits",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Record Locks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DB_testvm_20000_sports2020_SummaryRecLocks",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DB_testvm_20000_sports2020_BufferHits",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DB_testvm_20000_sports2020_PrimaryHits",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activity Records",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "DB_testvm_20000_sports2020_RecordCreates",
     "legendFormat": "__auto"
    },
    {
     "expr": "DB_testvm_20000_sports2020_RecordReads",
     "legendFormat": "__auto"
    },
    {
     "expr": "DB_testvm_20000_sports2020_RecordUpdates",
     "legendFormat": "__auto"
    },
    {
     "expr": "DB_testvm_20000_sports2020_RecordDeletes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Writes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DB_testvm_20000_sports2020_SummaryDbWrites",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Reads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DB_testvm_20000_sports2020_SummaryDbReads",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Record Creates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DB_testvm_20000_sports2020_RecordCreates",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Record Reads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DB_testvm_20000_sports2020_RecordReads",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BI Writes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DB_testvm_20000_sports2020_SummaryBiWrites",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BI Reads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DB_testvm_20000_sports2020_SummaryBiReads",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Record Updates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DB_testvm_20000_sports2020_RecordUpdates",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Record Deletes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DB_testvm_20000_sports2020_RecordDeletes",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PASOE - oepas1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "All Agents",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "PASOE_oepas1_AllAgentscount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Available Agents",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PASOE_oepas1_AvailableAgentscount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Agent Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PASOE_oepas1_AllAgentSessionscount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Client Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PASOE_oepas1_AllClientConnectionscount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Client Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PASOE_oepas1_AllClientSessionscount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "PASOE_oepas1_AllRequestsRequests",
     "legendFormat": "__auto"
    },
    {
     "expr": "PASOE_oepas1_ROOT_APSV_Requests_sessionRequests",
     "legendFormat": "__auto"
    },
    {
     "expr": "PASOE_oepas1_ROOT_REST_Requests_requests",
     "legendFormat": "__auto"
    },
    {
     "expr": "PASOE_oepas1_ROOT_SOAP_Requests_getRequests",
     "legendFormat": "__auto"
    },
    {
     "expr": "PASOE_oepas1_ROOT_WEB_Requests_getRequests",
     "legendFormat": "__auto"
    },
    {
     "expr": "PASOE_oepas1_ROOT_SOAP_Requests_soapRequests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PASOE_oepas1_AllRequestsRequests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APSV Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PASOE_oepas1_ROOT_APSV_Requests_sessionRequests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REST Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PASOE_oepas1_ROOT_REST_Requests_requests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SOAP Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PASOE_oepas1_ROOT_SOAP_Requests_soapRequests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PASOE_oepas1_ROOT_WEB_Requests_getRequests",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}