Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.220"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    # cd /vagrant
    # cp response.ini \
    #    PROGRESS_PASOE_CONTAINER_IMAGE_12.2.9_LNX_64.zip \
    #    PROGRESS_OE_12.2.9_LNX_64.tar.gz ~/Downloads

    if [ ! -d ~/openedge-demos ]
    then
      git clone https://github.com/progress/openedge-demos.git
    fi

    export WEBFILES=http://10.0.0.67:8080/pkgs
    ~/openedge-demos/pasoe_sample_app_using_scripts/scripts/install-demo.sh
  SHELL
end
