Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.synced_folder "c:/files", "/files"
  config.vm.synced_folder "../scripts", "/scripts"

  config.vm.network "private_network", ip: "192.168.56.226"

  config.vm.provision "os", type: "shell", inline: <<-SHELL
    # set -x
    if [ ! -f /usr/bin/jq ]
    then
      apt-get update
      apt-get install -y jq
    fi
  SHELL

  config.vm.provision "install_openjdk",
    type: "shell",
    path: "../scripts/install_openjdk.sh",
    args: "17"

  config.vm.provision "install_openedge",
    type: "shell",
    path: "../scripts/install_openedge.sh",
    args: "12.6"

end
